version: "3"
services:
  auth:
    container_name: "auth"
    build: ./auth
    ports:
      - "3000:3000"
    volumes:
      - ./auth:/auth
    depends_on:
      - db
    networks:
      - app

  db:
    image: mysql
    container_name: "db"
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app

networks:
  app:

volumes:
  database:
  rabbitmq_data:
